---
title: "SHDB"
author: "Jinshi"
date: "September 20, 2019"
output: html_document
---


## Load packages
```{r load R packages, message=FALSE, echo=FALSE, cache=TRUE}
# library("gridExtra")
# install.packages(c("agricolae","here","multcompView","ncdf4","bootstrap", "metafor",
#                    "cowplot", "data.table", "ggplot2", "lubridate", "kableExtra",
#                    "knitr", "ggpubr", "ggmap", "maps", "mapdata", 'dplyr'
#                    , "tidyr", "stringr"))
library(here)
library(agricolae)
# install.packages('multcompView')
library(multcompView)
# install.packages("ncdf4")
library(ncdf4)
# install.packages("bootstrap")
# install.packages("metafor")
library("metafor")
library("bootstrap")
library(cowplot)
library(data.table)
library(ggplot2)
theme_set(theme_bw())
library(lubridate)
library(kableExtra)
library(knitr)
library("ggpubr")
# library(reshape)
# install.packages("ggmap")
library(ggmap)
# install.packages("maps")
library(maps)
# install.packages("mapdata")
library(mapdata)
library(tidyr)
# install.packages('car')
library(car)
library(dplyr)
library(stringr)

# install.packages("tiff")
library(tiff)
library(raster)

source('RScripts/functions.R')
```



## Preliminary setup
```{r preliminaries, message=FALSE, include=FALSE, echo=FALSE, cache=FALSE}
# Set chunks defaults; these options will be applied to all subsequent chunks
knitr::opts_chunk$set(results = 'hide', message = TRUE, include = TRUE, echo = FALSE, cache = TRUE, warning = FALSE,
                      fig.height = 4, fig.width = 8)
 
```


## Load data
```{r load data1}

SoilHealthDB <- read.csv("data/SoilHealthDB_V1.csv", header = T)

koeppen <- read.table("data/other_data/Koeppen-Geiger-ASCII.txt", header = TRUE, sep = "")
IGBP <- read.table("data/other_data/IGBP2010Point.txt", header = TRUE, sep = ",")
ClimateDel <- read.csv("data/other_data/summarized_climate.csv")
DSMW_point <- read.csv("data/other_data/DSMW_Point.csv")
DSMW_soiltype <- read.csv("data/other_data/DSMW_SoilType.csv")

lat <- read.csv("data/other_data/lat.csv")
lon <- read.csv("data/other_data/lon.csv")
cec <- read.csv("data/other_data/T_Clay_CEC.csv")
wrb <- raster('data/WRB/wsrc_.tif')
wrb_point <- rasterToPoints(wrb)
wrb_point <- as.data.frame(wrb_point)
wrb_point %>% mutate(Lat_round = round(y*4)/4, Long_round = round(x*4)/4) -> wrb_point
SoilHealthDB %>% mutate(Lat_round = round(Latitude*4)/4, Long_round = round(Longitude*4)/4)
wrb_attributes <- read.csv("data/WRB/wrb.csv")
```

```{r}
SoilHealthDB %>% dplyr::select(Country) %>% unique() %>% arrange()
```

## Prepare data and calculation
```{r data calculation, message=TALSE}
# The following functions takes long time to finish
SoilHealthDB <- get_koeppon(SoilHealthDB, koeppen)
SoilHealthDB <- get_Del(SoilHealthDB, ClimateDel)
# SoilHealthDB <- get_soil(SoilHealthDB, DSMW_point)
SoilHealthDB <- get_cec(SoilHealthDB)
SoilHealthDB <- get_wrb(SoilHealthDB)
# left_join(SoilHealthDB, wrb_point %>% dplyr::select(Lat_round, Long_round, wsrc_), by=c("Lat_round", "Long_round"))
# left_join(SoilHealthDB, DSMW_soiltype %>% select(VALUE_, FAOSOIL), by = c("nDSMW" = "VALUE_")) -> SoilHealthDB # FAO soil classfication
left_join(SoilHealthDB, wrb_attributes, by = c("wrb" = "CASE")) -> SoilHealthDB
matrix_cec <- as.matrix(cec)
SoilHealthDB %>% mutate(KoeppenGroup = case_when(Koeppen %in% c("Af", "Am", "As", "Aw") ~ "Equat"
                                                 , Koeppen %in% c("BSh", "BSk", "BWh") ~ "Arid"
                                                 , Koeppen %in% c("Cfa", "Cfb", "Csa", "Csb", "Cwa", "Cwb") ~ "Temp"
                                                 , Koeppen %in% c("Dfa", "Dfb", "Dfc", "Dwa", "Dwb") ~ "Snow"
)) -> SoilHealthDB

# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^A")) %>% count() #867
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^B")) %>% count() #764
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^C")) %>% count() #40
# # SoilHealthDB %>% filter(str_detect(FAOSOIL, "^D")) %>% count(FAOSOIL)
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^E")) %>% count() #16
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^F")) %>% count() #705
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^G")) %>% count() #175
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^H")) %>% count() #534
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^I")) %>% count() #480
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^J")) %>% count() #230
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^K")) %>% count() #297
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^L")) %>% count() #935
# # SoilHealthDB %>% filter(str_detect(FAOSOIL, "^M")) %>% count(FAOSOIL)
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^N")) %>% count() #155
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^O")) %>% count() #2
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^P")) %>% count() #116
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^Q")) %>% count() #28
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^R")) %>% count() #72
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^S")) %>% count() #13
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^T")) %>% count() #35
# # SoilHealthDB %>% filter(str_detect(FAOSOIL, "^U")) %>% count(FAOSOIL)
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^V")) %>% count() #7
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^W")) %>% count() #235
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^X")) %>% count() #86
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^Y")) %>% count() #8
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "^Z")) %>% count() #18
# SoilHealthDB %>% filter(str_detect(FAOSOIL, "WAT")) %>% count() #183
```

## Plot samples spatial distribution
```{r plot site spatial distribution}
pdf("outputs/Figure 1.pdf", width = 8, height = 4)
print(plot_site(SoilHealthDB)) 
# ggsave("outputs/Figure 1.pdf", width = 8, height = 4, dpi = 300, units = "in")
dev.off()

```

## Plot climate and soil representation
```{r climate representation, fig.width=8, fig.height=8}
# Climate region plot
SoilHealthDB %>% filter(!is.na(KoeppenGroup)) %>% 
  ggplot(aes(KoeppenGroup)) + geom_bar() +
  labs(x=expression(Koeppen~climate), y="Count") -> plot_climate

# MAT plot
ClimateDel %>% filter(MAT > -5) %>% ggplot(aes(MAT)) +
  geom_density(stat = 'density', col = "black", fill = "gray") +
  geom_density(data = SoilHealthDB, aes(MAT_del), stat = 'density', col = "lightblue", fill = rgb(0,1,1, alpha = 0.5)) +
  labs(x=expression(MAT~"("~degree~C~")"), y="Density") -> plot_MAT

# MAP plot
sub_SlilHealthDB <- SoilHealthDB %>% filter(MAP_del > 300 & MAP_del<3000)
ClimateDel %>% filter(MAP > 300 & MAP < 3000) %>% ggplot(aes(MAP)) +
  geom_density(stat = 'density', col = "black", fill = "gray") +
  geom_density(data = sub_SlilHealthDB
               , aes(MAP_del), stat = 'density', col = "lightblue", fill = rgb(0,1,1, alpha = 0.5)) +
  labs(x=expression(MAP~"(mm)"), y="Density") -> plot_MAP

# plot soil classification group
# numbers please see Chunk3: load data
tibble( SoilClass = c("Acrisols(867)", "Cambisols(764)", "Chernozems(40)" ,"Rendzinas(16)","Ferralsols(705)"
                      ,"Gleysols(175)","Phaeozems(534)","Lithosols(438)","Fluvisols(230)"
                      ,"Kastanozems(297)","Luvisols(935)","Nitosols(155)","Histosols(2)"
                      ,"Podzols(116)","Arenosols(28)","Regosols(72)"
                      ,"Solonetz(13)","Andosols(35)","Vertisols(7)","Planosols(235)"
                      ,"Xerosols(86)","Yermosols(8)","Solonchaks(18)","Wetland(183)"),
        obs = c(867,764,40,16,705,175,534,480,230,297,935,155,2,116,28,72,13,35,7,235,86,8,18,183) ) %>% 
  ggplot(aes(x=SoilClass, y=obs)) + geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle=45, vjust = 1, hjust = 1)) +
  labs(x=expression(Soil~group), y="Samples (n)") -> plot_soilgroup

SoilHealthDB %>% filter(!is.na(DESCRIP)) %>% ggplot(aes(DESCRIP)) + geom_bar() +
  theme(axis.text.x = element_text(angle=45, vjust = 1, hjust = 1)) +
  labs(x=expression(WRB~soil~group), y="Count") -> plot_soilgroup2

# Combine all fanels for Figure 4
plot_grid(plot_climate, plot_MAT, plot_MAP, nrow = 1, labels = c("a", "b", "c"), hjust = c(-7.5, -7, -8.5), vjust = 2) -> p1
plot_grid(p1, plot_soilgroup2, ncol = 1, labels = c("", "d"), hjust = -7, vjust = 2) -> Fig4

pdf("outputs/Figure 4.pdf", width = 8, height = 8)
print(Fig4)
# ggsave("outputs/Figure 4.jpg", width = 8, height = 8, dpi = 300, units = "in")
dev.off()
```

## Plot CEC representation
```{r plot CEC repressentation, fig.height=6, fig.width=4}
# tiff("outputs/Figure 5.tiff", width = 6, height = 8, pointsize = 1/300, units = 'in', res = 300)
pdf("outputs/Figure 5.pdf", width = 6, height = 8)

par( mar=c(2, 0.2, 0.2, 0.2)
     , mai=c(0.3, 0.6, 0.1, 0.1)  # by inches, inner margin
     , omi = c(1.6, 0.3, 0.3, 0.1)  # by inches, outer margin 
     , mgp = c(0, 0.3, 0) # set distance of axis
     , tcl = 0.4
     , cex.axis = 1
     , las = 1
     , mfrow=c(2, 1))

# plot soilhealthDB
cec_db <- density(SoilHealthDB[SoilHealthDB$cec>0,]$cec, na.rm = TRUE)
plot(cec_db, main = ""
     , xaxt = "n", xlab = "" , col = "blue"
     , yaxt = "n", ylab = ""
     , xlim = c(0, 150), ylim = c(0, 0.030)
)
polygon(cec_db, col = "lightblue")

# mtext(1,text = expression(CEC), line = 1.75, cex=1)
mtext(2,text = expression("Density"), line = 2.75, cex=1, las = 0)
text(10, 0.028,"a", cex=1, lwd = 2)
axis(side=1,las=1,cex=1,tcl=0.4, at = seq(0,150,30))
axis(side=2,las=1,cex=1,tcl=0.4, at = seq(0,0.03,0.01))

# SoilHealthDB <- get_cec(SoilHealthDB)
matrix_cec <- as.matrix(cec)
cec_dens <- density(matrix_cec, na.rm = TRUE)
plot(cec_dens, main = ""
     , xaxt = "n", xlab = ""
     , yaxt = "n", ylab = ""
     , xlim = c(0, 150), ylim = c(0, 0.030)
)
polygon(cec_dens, col = "gray")

mtext(1,text = expression(CEC), line = 1.75, cex=1)
mtext(2,text = expression("Density"), line = 2.75, cex=1, las = 0)
text(10, 0.028,"b", cex=1, lwd = 2)
axis(side=1,las=1,cex=1,tcl=0.4, at = seq(0,150,30))
axis(side=2,las=1,cex=1,tcl=0.4, at = seq(0,0.03,0.01))

dev.off()
```

## Test code
```{r}
# plot(density(wrb, na.rm = TRUE))
# image(wrb)
# 
# rasterToPoints(wrb)
```

